[build]
builder = "nixpacks"

[deploy]
startCommand= "npx prisma db push --accept-data-loss && node dist/index.js"
#startCommand = "npx prisma migrate deploy && node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 60
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
