/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace OrchestratorEscrow {
  export type SubtaskStruct = {
    taskId: BigNumberish;
    subtaskIndex: BigNumberish;
    agentWallet: AddressLike;
    capability: BytesLike;
    budget: BigNumberish;
    deliverableHash: BytesLike;
    description: string;
    status: BigNumberish;
    assignedAt: BigNumberish;
    settledAt: BigNumberish;
  };

  export type SubtaskStructOutput = [
    taskId: bigint,
    subtaskIndex: bigint,
    agentWallet: string,
    capability: string,
    budget: bigint,
    deliverableHash: string,
    description: string,
    status: bigint,
    assignedAt: bigint,
    settledAt: bigint
  ] & {
    taskId: bigint;
    subtaskIndex: bigint;
    agentWallet: string;
    capability: string;
    budget: bigint;
    deliverableHash: string;
    description: string;
    status: bigint;
    assignedAt: bigint;
    settledAt: bigint;
  };

  export type TaskStruct = {
    id: BigNumberish;
    requester: AddressLike;
    description: string;
    totalBudget: BigNumberish;
    allocatedBudget: BigNumberish;
    subtaskCount: BigNumberish;
    settledCount: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    expiresAt: BigNumberish;
  };

  export type TaskStructOutput = [
    id: bigint,
    requester: string,
    description: string,
    totalBudget: bigint,
    allocatedBudget: bigint,
    subtaskCount: bigint,
    settledCount: bigint,
    status: bigint,
    createdAt: bigint,
    expiresAt: bigint
  ] & {
    id: bigint;
    requester: string;
    description: string;
    totalBudget: bigint;
    allocatedBudget: bigint;
    subtaskCount: bigint;
    settledCount: bigint;
    status: bigint;
    createdAt: bigint;
    expiresAt: bigint;
  };
}

export interface OrchestratorEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "MAX_SUBTASKS"
      | "ORCHESTRATOR_ROLE"
      | "TASK_EXPIRY"
      | "USDC"
      | "assignSubtask"
      | "cancelTask"
      | "completeTask"
      | "createTask"
      | "disputeSubtask"
      | "feeRecipient"
      | "getRoleAdmin"
      | "getSubtask"
      | "getSubtasks"
      | "getTask"
      | "grantRole"
      | "hasRole"
      | "nextTaskId"
      | "platformFeeBps"
      | "registry"
      | "renounceRole"
      | "revokeRole"
      | "serviceFeeBps"
      | "setFeeRecipient"
      | "setPlatformFee"
      | "setServiceFee"
      | "settleSubtask"
      | "submitDeliverable"
      | "subtasks"
      | "supportsInterface"
      | "tasks"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DeliverableSubmitted"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "ServiceFeeCharged"
      | "SubtaskAssigned"
      | "SubtaskDisputed"
      | "SubtaskSettled"
      | "TaskCancelled"
      | "TaskCompleted"
      | "TaskCreated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_SUBTASKS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ORCHESTRATOR_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "TASK_EXPIRY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "USDC", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "assignSubtask",
    values: [BigNumberish, AddressLike, BytesLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "cancelTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createTask",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "disputeSubtask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubtask",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubtasks",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTask",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nextTaskId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "serviceFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeRecipient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setServiceFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settleSubtask",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitDeliverable",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subtasks",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tasks", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_SUBTASKS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "ORCHESTRATOR_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "TASK_EXPIRY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "USDC", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "assignSubtask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "completeTask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createTask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "disputeSubtask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getSubtask", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSubtasks",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTask", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextTaskId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "serviceFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFeeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setServiceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "settleSubtask",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitDeliverable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subtasks", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tasks", data: BytesLike): Result;
}

export namespace DeliverableSubmittedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    subtaskIndex: BigNumberish,
    deliverableHash: BytesLike
  ];
  export type OutputTuple = [
    taskId: bigint,
    subtaskIndex: bigint,
    deliverableHash: string
  ];
  export interface OutputObject {
    taskId: bigint;
    subtaskIndex: bigint;
    deliverableHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ServiceFeeChargedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    grossBudget: BigNumberish,
    serviceFee: BigNumberish,
    netBudget: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    grossBudget: bigint,
    serviceFee: bigint,
    netBudget: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    grossBudget: bigint;
    serviceFee: bigint;
    netBudget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubtaskAssignedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    subtaskIndex: BigNumberish,
    agent: AddressLike,
    budget: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    subtaskIndex: bigint,
    agent: string,
    budget: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    subtaskIndex: bigint;
    agent: string;
    budget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubtaskDisputedEvent {
  export type InputTuple = [taskId: BigNumberish, subtaskIndex: BigNumberish];
  export type OutputTuple = [taskId: bigint, subtaskIndex: bigint];
  export interface OutputObject {
    taskId: bigint;
    subtaskIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubtaskSettledEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    subtaskIndex: BigNumberish,
    agent: AddressLike,
    amount: BigNumberish,
    completionBps: BigNumberish
  ];
  export type OutputTuple = [
    taskId: bigint,
    subtaskIndex: bigint,
    agent: string,
    amount: bigint,
    completionBps: bigint
  ];
  export interface OutputObject {
    taskId: bigint;
    subtaskIndex: bigint;
    agent: string;
    amount: bigint;
    completionBps: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCancelledEvent {
  export type InputTuple = [taskId: BigNumberish, refundAmount: BigNumberish];
  export type OutputTuple = [taskId: bigint, refundAmount: bigint];
  export interface OutputObject {
    taskId: bigint;
    refundAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [taskId: BigNumberish];
  export type OutputTuple = [taskId: bigint];
  export interface OutputObject {
    taskId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCreatedEvent {
  export type InputTuple = [
    taskId: BigNumberish,
    requester: AddressLike,
    budget: BigNumberish
  ];
  export type OutputTuple = [taskId: bigint, requester: string, budget: bigint];
  export interface OutputObject {
    taskId: bigint;
    requester: string;
    budget: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface OrchestratorEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): OrchestratorEscrow;
  waitForDeployment(): Promise<this>;

  interface: OrchestratorEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  MAX_SUBTASKS: TypedContractMethod<[], [bigint], "view">;

  ORCHESTRATOR_ROLE: TypedContractMethod<[], [string], "view">;

  TASK_EXPIRY: TypedContractMethod<[], [bigint], "view">;

  USDC: TypedContractMethod<[], [string], "view">;

  assignSubtask: TypedContractMethod<
    [
      taskId: BigNumberish,
      agentWallet: AddressLike,
      capability: BytesLike,
      budget: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;

  cancelTask: TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;

  completeTask: TypedContractMethod<
    [taskId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createTask: TypedContractMethod<
    [description: string, budget: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  disputeSubtask: TypedContractMethod<
    [taskId: BigNumberish, subtaskIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getSubtask: TypedContractMethod<
    [taskId: BigNumberish, index: BigNumberish],
    [OrchestratorEscrow.SubtaskStructOutput],
    "view"
  >;

  getSubtasks: TypedContractMethod<
    [taskId: BigNumberish],
    [OrchestratorEscrow.SubtaskStructOutput[]],
    "view"
  >;

  getTask: TypedContractMethod<
    [taskId: BigNumberish],
    [OrchestratorEscrow.TaskStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  nextTaskId: TypedContractMethod<[], [bigint], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  serviceFeeBps: TypedContractMethod<[], [bigint], "view">;

  setFeeRecipient: TypedContractMethod<
    [recipient: AddressLike],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [bps: BigNumberish],
    [void],
    "nonpayable"
  >;

  setServiceFee: TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;

  settleSubtask: TypedContractMethod<
    [
      taskId: BigNumberish,
      subtaskIndex: BigNumberish,
      completionBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  submitDeliverable: TypedContractMethod<
    [
      taskId: BigNumberish,
      subtaskIndex: BigNumberish,
      deliverableHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  subtasks: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        taskId: bigint;
        subtaskIndex: bigint;
        agentWallet: string;
        capability: string;
        budget: bigint;
        deliverableHash: string;
        description: string;
        status: bigint;
        assignedAt: bigint;
        settledAt: bigint;
      }
    ],
    "view"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  tasks: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        requester: string;
        description: string;
        totalBudget: bigint;
        allocatedBudget: bigint;
        subtaskCount: bigint;
        settledCount: bigint;
        status: bigint;
        createdAt: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MAX_SUBTASKS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ORCHESTRATOR_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "TASK_EXPIRY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "USDC"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "assignSubtask"
  ): TypedContractMethod<
    [
      taskId: BigNumberish,
      agentWallet: AddressLike,
      capability: BytesLike,
      budget: BigNumberish,
      description: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "cancelTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeTask"
  ): TypedContractMethod<[taskId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createTask"
  ): TypedContractMethod<
    [description: string, budget: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "disputeSubtask"
  ): TypedContractMethod<
    [taskId: BigNumberish, subtaskIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSubtask"
  ): TypedContractMethod<
    [taskId: BigNumberish, index: BigNumberish],
    [OrchestratorEscrow.SubtaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getSubtasks"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [OrchestratorEscrow.SubtaskStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTask"
  ): TypedContractMethod<
    [taskId: BigNumberish],
    [OrchestratorEscrow.TaskStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextTaskId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "serviceFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFeeRecipient"
  ): TypedContractMethod<[recipient: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setServiceFee"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settleSubtask"
  ): TypedContractMethod<
    [
      taskId: BigNumberish,
      subtaskIndex: BigNumberish,
      completionBps: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "submitDeliverable"
  ): TypedContractMethod<
    [
      taskId: BigNumberish,
      subtaskIndex: BigNumberish,
      deliverableHash: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subtasks"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [
        bigint,
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint
      ] & {
        taskId: bigint;
        subtaskIndex: bigint;
        agentWallet: string;
        capability: string;
        budget: bigint;
        deliverableHash: string;
        description: string;
        status: bigint;
        assignedAt: bigint;
        settledAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "tasks"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        requester: string;
        description: string;
        totalBudget: bigint;
        allocatedBudget: bigint;
        subtaskCount: bigint;
        settledCount: bigint;
        status: bigint;
        createdAt: bigint;
        expiresAt: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "DeliverableSubmitted"
  ): TypedContractEvent<
    DeliverableSubmittedEvent.InputTuple,
    DeliverableSubmittedEvent.OutputTuple,
    DeliverableSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "ServiceFeeCharged"
  ): TypedContractEvent<
    ServiceFeeChargedEvent.InputTuple,
    ServiceFeeChargedEvent.OutputTuple,
    ServiceFeeChargedEvent.OutputObject
  >;
  getEvent(
    key: "SubtaskAssigned"
  ): TypedContractEvent<
    SubtaskAssignedEvent.InputTuple,
    SubtaskAssignedEvent.OutputTuple,
    SubtaskAssignedEvent.OutputObject
  >;
  getEvent(
    key: "SubtaskDisputed"
  ): TypedContractEvent<
    SubtaskDisputedEvent.InputTuple,
    SubtaskDisputedEvent.OutputTuple,
    SubtaskDisputedEvent.OutputObject
  >;
  getEvent(
    key: "SubtaskSettled"
  ): TypedContractEvent<
    SubtaskSettledEvent.InputTuple,
    SubtaskSettledEvent.OutputTuple,
    SubtaskSettledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCancelled"
  ): TypedContractEvent<
    TaskCancelledEvent.InputTuple,
    TaskCancelledEvent.OutputTuple,
    TaskCancelledEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCreated"
  ): TypedContractEvent<
    TaskCreatedEvent.InputTuple,
    TaskCreatedEvent.OutputTuple,
    TaskCreatedEvent.OutputObject
  >;

  filters: {
    "DeliverableSubmitted(uint256,uint256,bytes32)": TypedContractEvent<
      DeliverableSubmittedEvent.InputTuple,
      DeliverableSubmittedEvent.OutputTuple,
      DeliverableSubmittedEvent.OutputObject
    >;
    DeliverableSubmitted: TypedContractEvent<
      DeliverableSubmittedEvent.InputTuple,
      DeliverableSubmittedEvent.OutputTuple,
      DeliverableSubmittedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "ServiceFeeCharged(uint256,uint256,uint256,uint256)": TypedContractEvent<
      ServiceFeeChargedEvent.InputTuple,
      ServiceFeeChargedEvent.OutputTuple,
      ServiceFeeChargedEvent.OutputObject
    >;
    ServiceFeeCharged: TypedContractEvent<
      ServiceFeeChargedEvent.InputTuple,
      ServiceFeeChargedEvent.OutputTuple,
      ServiceFeeChargedEvent.OutputObject
    >;

    "SubtaskAssigned(uint256,uint256,address,uint256)": TypedContractEvent<
      SubtaskAssignedEvent.InputTuple,
      SubtaskAssignedEvent.OutputTuple,
      SubtaskAssignedEvent.OutputObject
    >;
    SubtaskAssigned: TypedContractEvent<
      SubtaskAssignedEvent.InputTuple,
      SubtaskAssignedEvent.OutputTuple,
      SubtaskAssignedEvent.OutputObject
    >;

    "SubtaskDisputed(uint256,uint256)": TypedContractEvent<
      SubtaskDisputedEvent.InputTuple,
      SubtaskDisputedEvent.OutputTuple,
      SubtaskDisputedEvent.OutputObject
    >;
    SubtaskDisputed: TypedContractEvent<
      SubtaskDisputedEvent.InputTuple,
      SubtaskDisputedEvent.OutputTuple,
      SubtaskDisputedEvent.OutputObject
    >;

    "SubtaskSettled(uint256,uint256,address,uint256,uint256)": TypedContractEvent<
      SubtaskSettledEvent.InputTuple,
      SubtaskSettledEvent.OutputTuple,
      SubtaskSettledEvent.OutputObject
    >;
    SubtaskSettled: TypedContractEvent<
      SubtaskSettledEvent.InputTuple,
      SubtaskSettledEvent.OutputTuple,
      SubtaskSettledEvent.OutputObject
    >;

    "TaskCancelled(uint256,uint256)": TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;
    TaskCancelled: TypedContractEvent<
      TaskCancelledEvent.InputTuple,
      TaskCancelledEvent.OutputTuple,
      TaskCancelledEvent.OutputObject
    >;

    "TaskCompleted(uint256)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;

    "TaskCreated(uint256,address,uint256)": TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
    TaskCreated: TypedContractEvent<
      TaskCreatedEvent.InputTuple,
      TaskCreatedEvent.OutputTuple,
      TaskCreatedEvent.OutputObject
    >;
  };
}
