/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AgentCapabilityRegistry {
  export type AgentStruct = {
    wallet: AddressLike;
    erc8004AgentId: BigNumberish;
    name: string;
    description: string;
    metadataURI: string;
    capabilities: BytesLike[];
    pricePerTask: BigNumberish;
    totalJobsCompleted: BigNumberish;
    totalEarned: BigNumberish;
    active: boolean;
    registeredAt: BigNumberish;
  };

  export type AgentStructOutput = [
    wallet: string,
    erc8004AgentId: bigint,
    name: string,
    description: string,
    metadataURI: string,
    capabilities: string[],
    pricePerTask: bigint,
    totalJobsCompleted: bigint,
    totalEarned: bigint,
    active: boolean,
    registeredAt: bigint
  ] & {
    wallet: string;
    erc8004AgentId: bigint;
    name: string;
    description: string;
    metadataURI: string;
    capabilities: string[];
    pricePerTask: bigint;
    totalJobsCompleted: bigint;
    totalEarned: bigint;
    active: boolean;
    registeredAt: bigint;
  };
}

export interface AgentCapabilityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_CAPABILITIES"
      | "MIN_PRICE"
      | "agents"
      | "allAgents"
      | "deactivate"
      | "getAgent"
      | "getAgentsByCapability"
      | "getAllAgents"
      | "hashCapability"
      | "isRegistered"
      | "owner"
      | "recordJobCompletion"
      | "registerAgent"
      | "renounceOwnership"
      | "transferOwnership"
      | "updateAgent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentDeactivated"
      | "AgentRegistered"
      | "AgentStatsUpdated"
      | "AgentUpdated"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_CAPABILITIES",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MIN_PRICE", values?: undefined): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "allAgents",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAgentsByCapability",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAgents",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hashCapability",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordJobCompletion",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [BigNumberish, string, string, string, BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateAgent",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_CAPABILITIES",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "MIN_PRICE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "allAgents", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deactivate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAgentsByCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "hashCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordJobCompletion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateAgent",
    data: BytesLike
  ): Result;
}

export namespace AgentDeactivatedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    wallet: AddressLike,
    erc8004AgentId: BigNumberish,
    name: string
  ];
  export type OutputTuple = [
    wallet: string,
    erc8004AgentId: bigint,
    name: string
  ];
  export interface OutputObject {
    wallet: string;
    erc8004AgentId: bigint;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentStatsUpdatedEvent {
  export type InputTuple = [
    wallet: AddressLike,
    jobsCompleted: BigNumberish,
    totalEarned: BigNumberish
  ];
  export type OutputTuple = [
    wallet: string,
    jobsCompleted: bigint,
    totalEarned: bigint
  ];
  export interface OutputObject {
    wallet: string;
    jobsCompleted: bigint;
    totalEarned: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentCapabilityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentCapabilityRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentCapabilityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_CAPABILITIES: TypedContractMethod<[], [bigint], "view">;

  MIN_PRICE: TypedContractMethod<[], [bigint], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        wallet: string;
        erc8004AgentId: bigint;
        name: string;
        description: string;
        metadataURI: string;
        pricePerTask: bigint;
        totalJobsCompleted: bigint;
        totalEarned: bigint;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  allAgents: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deactivate: TypedContractMethod<[], [void], "nonpayable">;

  getAgent: TypedContractMethod<
    [wallet: AddressLike],
    [AgentCapabilityRegistry.AgentStructOutput],
    "view"
  >;

  getAgentsByCapability: TypedContractMethod<
    [capability: BytesLike],
    [string[]],
    "view"
  >;

  getAllAgents: TypedContractMethod<[], [string[]], "view">;

  hashCapability: TypedContractMethod<[cap: string], [string], "view">;

  isRegistered: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordJobCompletion: TypedContractMethod<
    [agentWallet: AddressLike, earnedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerAgent: TypedContractMethod<
    [
      erc8004AgentId: BigNumberish,
      name: string,
      description: string,
      metadataURI: string,
      capabilities: BytesLike[],
      pricePerTask: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateAgent: TypedContractMethod<
    [metadataURI: string, pricePerTask: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_CAPABILITIES"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_PRICE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [
        string,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint
      ] & {
        wallet: string;
        erc8004AgentId: bigint;
        name: string;
        description: string;
        metadataURI: string;
        pricePerTask: bigint;
        totalJobsCompleted: bigint;
        totalEarned: bigint;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "allAgents"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deactivate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [wallet: AddressLike],
    [AgentCapabilityRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAgentsByCapability"
  ): TypedContractMethod<[capability: BytesLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getAllAgents"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "hashCapability"
  ): TypedContractMethod<[cap: string], [string], "view">;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordJobCompletion"
  ): TypedContractMethod<
    [agentWallet: AddressLike, earnedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      erc8004AgentId: BigNumberish,
      name: string,
      description: string,
      metadataURI: string,
      capabilities: BytesLike[],
      pricePerTask: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateAgent"
  ): TypedContractMethod<
    [metadataURI: string, pricePerTask: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentDeactivated"
  ): TypedContractEvent<
    AgentDeactivatedEvent.InputTuple,
    AgentDeactivatedEvent.OutputTuple,
    AgentDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentStatsUpdated"
  ): TypedContractEvent<
    AgentStatsUpdatedEvent.InputTuple,
    AgentStatsUpdatedEvent.OutputTuple,
    AgentStatsUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "AgentDeactivated(address)": TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;
    AgentDeactivated: TypedContractEvent<
      AgentDeactivatedEvent.InputTuple,
      AgentDeactivatedEvent.OutputTuple,
      AgentDeactivatedEvent.OutputObject
    >;

    "AgentRegistered(address,uint256,string)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentStatsUpdated(address,uint256,uint256)": TypedContractEvent<
      AgentStatsUpdatedEvent.InputTuple,
      AgentStatsUpdatedEvent.OutputTuple,
      AgentStatsUpdatedEvent.OutputObject
    >;
    AgentStatsUpdated: TypedContractEvent<
      AgentStatsUpdatedEvent.InputTuple,
      AgentStatsUpdatedEvent.OutputTuple,
      AgentStatsUpdatedEvent.OutputObject
    >;

    "AgentUpdated(address)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
