/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IAgentCapabilityRegistry,
  IAgentCapabilityRegistryInterface,
} from "../../../src/OrchestratorEscrow.sol/IAgentCapabilityRegistry";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "agentWallet",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "earnedAmount",
        type: "uint256",
      },
    ],
    name: "recordJobCompletion",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAgentCapabilityRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IAgentCapabilityRegistryInterface {
    return new Interface(_abi) as IAgentCapabilityRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IAgentCapabilityRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IAgentCapabilityRegistry;
  }
}
